"""Builds template.docx (and template.js) from the original contract.

Each highlighted section of the contract becomes a {{placeholder}} in a single
run, and the yellow highlight is removed so the generated contract is clean.
All prices are also turned into placeholders, so no pricing is stored in this
(public) repo. Staff enter prices in the form, or keep a private pricing link.
Re-run this if the source contract wording changes:
    python tools/build_template.py "path/to/contract.docx"
"""
import base64, sys, pathlib, docx

HERE = pathlib.Path(__file__).resolve().parent.parent
SRC = sys.argv[1] if len(sys.argv) > 1 else str(HERE.parent / "Click2Check  Contract - Quilter FS  2026.docx")

d = docx.Document(SRC)

def put(runs, idx, text, clear=()):
    runs[idx].text = text
    for i in clear:
        runs[i].text = ""

def expect(runs, idx, what):
    # Every run we replace must be one of the highlighted sections in the source contract
    bad = [i for i in idx if runs[i].font.highlight_color is None]
    assert not bad, f"Contract layout changed: expected the {what} to be highlighted (runs {bad})"

# --- Opening paragraph (parties) ---
p = d.paragraphs[3]; r = p.runs
expect(r, range(1, 6), "contract date")
expect(r, [13], "company name")
expect(r, [16], "short name"); expect(r, [23], "trading name")
expect(r, [27], "company number"); expect(r, range(31, 36), "registered address")
expect(r, [37], "short name"); expect(r, [42], "phone number")
put(r, 1, "{{contract_date}}", clear=range(2, 6))
put(r, 13, "{{company_name}}")
put(r, 16, "{{short_name}}")
put(r, 23, "{{trading_name}}")
put(r, 27, "{{company_reg}}")
put(r, 31, "{{registered_address}} ", clear=range(32, 36))
put(r, 37, "{{short_name}}")
put(r, 42, "{{phone}}")

# --- Signature block ---
p = d.tables[1].rows[1].cells[0].paragraphs[4]; r = p.runs
hl = [run for run in r if run.font.highlight_color is not None]
assert len(hl) == 2, f"Contract layout changed: expected 2 highlighted runs in the signature block, found {len(hl)}"
hl[0].text = "{{director_name}}"
hl[1].text = "{{company_name}}"

# --- Fee sheet ---
def cell_runs(row):
    return d.tables[2].rows[row].cells[1].paragraphs[0].runs
r = cell_runs(1); expect(r, range(len(r)), "monthly fee")
put(r, 0, "{{monthly_fee}}", clear=range(1, len(r)))
r = cell_runs(3); expect(r, range(len(r)), "subscription amount")
put(r, 0, "{{subscription_amount}}", clear=range(1, len(r)))
r = cell_runs(5); expect(r, range(len(r)), "total usage")
put(r, 0, "{{total_usage}}", clear=range(1, len(r)))

# --- Remaining prices (not highlighted in the source, but kept out of the public template) ---
def set_cell(table, row, col, text):
    runs = d.tables[table].rows[row].cells[col].paragraphs[0].runs
    assert "£" in "".join(x.text for x in runs), f"Contract layout changed: no price in table {table} row {row}"
    put(runs, 0, text, clear=range(1, len(runs)))

# Administration charge example table
set_cell(0, 0, 1, "{{credit_file_fee}}")
set_cell(0, 1, 1, "{{admin_fee}}")
set_cell(0, 2, 1, "{{example_total}}")
# Fee sheet: report price, set-up fee and set-up charge
r = d.tables[2].rows[2].cells[1].paragraphs[0].runs
assert r[0].text.startswith("£"), "Contract layout changed: report price"
r[0].text = "{{report_price}}"
r = d.tables[2].rows[4].cells[0].paragraphs[0].runs
i = next(i for i, x in enumerate(r) if x.text.startswith("£"))
r[i].text = "{{setup_fee}}"
set_cell(2, 4, 1, "{{setup_charged}}")

# --- Strip every yellow highlight ---
from docx.oxml.ns import qn
for el in d.element.body.iter(qn("w:highlight")):
    el.getparent().remove(el)

out = HERE / "template.docx"
d.save(out)
(HERE / "template.js").write_text(
    "// Generated by tools/build_template.py - do not edit by hand.\n"
    "window.CONTRACT_TEMPLATE_B64 = \"" + base64.b64encode(out.read_bytes()).decode() + "\";\n")
print("wrote", out)
